apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: test-app
  labels:
    app: guestbook-test
    tier: frontend
spec:
  # modify the replicas
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5

