apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
spec:
  containers:
  - name: my-container
    image: nginx:1.12.0
  initContainers:
  - name: my-init-container
    image: busybox
    command: ['sh', '-c', 'echo "Init Container executed"']
