apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: mycontainer
    image: nginx:latest
  tolerations:
  - key: "critical-workload"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
