apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.10
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: certs-volume
          mountPath: /etc/nginx/certs
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
            items:
            - key: nginx.conf
              path: nginx.conf
        - name: certs-volume
          secret:
            secretName: nginx-certs
