apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: test-app
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /run/nginx.pid;
    
    events {
      worker_connections  1024;
    }
    
    http {
      server {
        listen 443 ssl;
        server_name localhost;
      
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
      
        location / {
          return 200 'Hello from Nginx over HTTPS!';
          add_header Content-Type text/plain;
        }
      }
    }

